name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    workflow_dispatch:
    workflow_run:
      workflows: ["Build and Test"]
      types:
        - completed
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              run:
                echo "building..."
            - name: set up Node.js
              run:
                echo "setting up Node.js..."
                apt-get update

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Deploy application
              run: echo "deploying..."